[aliases]
l = ["log", "-r", "(master..@):: | (master..@)-"]
sl = ["log", "-l", "20"]
al = ["log", "-r", "all()"]
mylog = ["log", "-r", "author('peder.galteland@softwarelab.no')"]

[ui]
default-command = "st"
diff-editor = "vimdirdiff"

[ui.diff]
tool = ["difft", "--color=always", "$left", "$right"]

[user]
email = "peder.galteland@softwarelab.no"
name = "Peder Notto Galteland"

[signing]
# sign-all = true
backend = "gpg"
key = "4980821A221FE5B1"

[git]
push-bookmark-prefix = "pedernot/push-"

[fix.tools.ruff-fix]
command = ["ruff", "check", "--fix"]
patterns = ["glob:'**/*.py'"]

[fix.tools.ruff-format]
command = ["ruff", "format"]
patterns = ["glob:'**/*.py'"]
