source "$HOME/.nix-profile/etc/profile.d/nix.sh"
# Export default programs
export EDITOR="nvim"

# Path
export PATH="$XDG_DATA_HOME/cargo/bin:$PATH"
export PATH="$XDG_DATA_HOME/poetry/bin:$PATH"
export GOPATH=~/workspace/go
export PATH="$GOPATH/bin:$PATH"
export PATH="$XDG_DATA_HOME/gem/bin:$PATH"
export PATH="$XDG_DATA_HOME/npm/bin:$PATH"
export PATH="$HOME/.local/bin:$PATH"

# Overrides for applications not respecting XDG dirs
export _Z_DATA="$XDG_DATA_HOME/z"
export AWS_CONFIG_FILE="$XDG_CONFIG_HOME"/aws/config
export AWS_SHARED_CREDENTIALS_FILE="$XDG_CONFIG_HOME"/aws/credentials
export AZURE_CONFIG_DIR=$XDG_DATA_HOME/azure
export CARGO_HOME="$XDG_DATA_HOME"/cargo
export DOCKER_CONFIG="$XDG_CONFIG_HOME"/docker
export GEM_HOME="$XDG_DATA_HOME"/gem
export GEM_SPEC_CACHE="$XDG_CACHE_HOME"/gem
export GNUPGHOME="$XDG_DATA_HOME"/gnupg
export HTTPIE_CONFIG_DIR="$XDG_CONFIG_HOME"/httpie
export IPYTHONDIR="$XDG_CONFIG_HOME"/jupyter
export JUPYTER_CONFIG_DIR="$XDG_CONFIG_HOME"/jupyter
export KUBECONFIG="$XDG_CONFIG_HOME"/kube/config
export LESSHISTFILE="$XDG_CACHE_HOME"/less/history
export LESSKEY="$XDG_CONFIG_HOME"/less/lesskey
export NOTMUCH_CONFIG="$XDG_CONFIG_HOME"/notmuch/notmuchrc
export NPM_CONFIG_USERCONFIG=$XDG_CONFIG_HOME/npm/npmrc
export PASSWORD_STORE_DIR="$XDG_DATA_HOME"/pass
export PLTUSERHOME="$XDG_DATA_HOME"/racket
export POETRY_HOME="$XDG_CACHE_HOME"/poetry
export PSQL_HISTORY="$XDG_CACHE_HOME/pg/psql_history"
export PYLINTHOME="$XDG_CACHE_HOME"/pylint
export RANDFILE="$XDG_CACHE_HOME"/openssl/rnd
export RUSTUP_HOME="$XDG_DATA_HOME"/rustup
export STACK_ROOT="$XDG_DATA_HOME"/stack
export TERMINFO="$XDG_DATA_HOME"/terminfo
export TERMINFO_DIRS="$XDG_DATA_HOME"/terminfo:/usr/share/terminfo
export WGETRC="$XDG_CONFIG_HOME/wgetrc"
export XAUTHORITY="$XDG_RUNTIME_DIR"/Xauthority
export XINITRC="$XDG_CONFIG_HOME"/X11/xinitrc

# Custom python startup script
export PYTHONSTARTUP="$XDG_CONFIG_HOME"/python/startup.py

# Set up gpg as ssh-agent
if [ -z "$SSH_CLIENT" ]; then
  export GPG_TTY="$(tty)"
  export SSH_AUTH_SOCK=$(gpgconf --list-dirs agent-ssh-socket)
  gpgconf --launch gpg-agent
fi

source $XDG_DATA_HOME/cargo/env
